name: Create Pull Request
on:
  push:
    branches:
      - develop # 觸發分支
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Pull Request Title
          body: Pull Request Description
          branch: develop
          base: main
          token: ${{ secrets.MY_GITHUB_TOKEN }}
